Fix error: 'Z_MIN' was not declared in this scope
File endstop_ISR.h is moved from HAL/HAL_STM32_F4_F7
to HAL/STM32 instead of being removed.

Revert "Switch to STM32 HAL."
This reverts commit 676c669113a7c0bff4ec8f989f8bb0c50b657e8e.

Revert "Remove non-existing header file include."
This reverts commit 23b099ba89f10b9ef99e8f2145469b4f177adbcc.